version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACE_TASK_DEFINITION_ARN"
        LoadBalancerInfo:
          ContainerName: "node-app"
          ContainerPort: 8080
